apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-preflight-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-preflight-controller
subjects:
  - kind: ServiceAccount
    name: platform-preflight-controller
    namespace: platform-preflight-system
